jobs:
  deploy:
    environment: env        # <-- unlocks environment secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java and configure Maven + GPG
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME   # env var name
          server-password: CENTRAL_PASSWORD   # env var name
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          GPG_PASSPHRASE:  ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and publish (Central plugin)
        run: mvn -B -DskipTests deploy
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
