name: Release to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java and configure Maven + GPG
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          # This writes <server id="central"> into settings.xml
          server-id: central
          server-username: ${{ secrets.CENTRAL_USERNAME }}
          server-password: ${{ secrets.CENTRAL_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Verify imported GPG key
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Build and publish (Central plugin)
        run: mvn -B -DskipTests deploy
        env:
          # Let maven-gpg-plugin read passphrase via env, not CLI
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
