name: Release to Maven Central

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Import GPG private key
        run: |
          mkdir -p ~/.gnupg
          # import ASCII-armored private key from secret
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          # allow loopback pinentry so maven-gpg-plugin can provide passphrase
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent || true

      - name: Create Maven settings.xml with OSSRH credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'SETTINGS'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>ossrh</id>
                <username>${env.OSSRH_USERNAME}</username>
                <password>${env.OSSRH_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          SETTINGS

      - name: Build and deploy (signed)
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn -B -Dgpg.passphrase="${GPG_PASSPHRASE}" -DskipTests clean deploy
