name: Release to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java and configure Maven + GPG
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Verify imported GPG key
        run: |
          gpg --list-secret-keys --keyid-format LONG

      - name: Build and deploy (signed)
        run: |
          mvn -B -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -DskipTests clean deploy
